server:
  port: 8888

# SDK 调用配置的base_url：https://dashscope.aliyuncs.com/compatible-mode/v1
# HTTP 请求地址：POST https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

spring:
  ai:
    chat:
      client:
        # 关闭自动装配 ChatClient 默认只会装配一个
        enabled: false
  webflux:
#    base-path: http://localhost:8888

aix:
  llm:
    chat:
      - platform: "dashscope"
        model: "deepseek-plus"
        api-key: ""
        base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        executor: ""
        desc: "通义千问"

      - platform: "dashscope"
        model: "deepseek-max"
        api-key: ""
        base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        executor: ""
        desc: "通义千问"

      - platform: "deepseek"
        model: "deepseek-max"
        api-key: ""
        base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        executor: ""
        desc: "通义千问"

    image:
      - platform: "dashscope"
        model: "deepseek-plus"
        api-key: ""
        base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        executor: ""
        desc: "通义千问"

      - platform: "dashscope"
        model: "deepseek-max"
        api-key: ""
        base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        executor: ""
        desc: "通义千问"

      - platform: "deepseek"
        model: "deepseek-max"
        api-key: ""
        base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        executor: ""
        desc: "通义千问"